version: '3'

services:
  llvm-lab:
    build: ./
    volumes:
      - ./share:/home/llvm-lab
      - ./xinetd:/etc/xinetd.d/llvm-lab
    cap_add:
      - SYS_PTRACE
    ports:
      - "30208:10101"
    expose:
      - "10101"
